### PR TITLE
Use .zip files instead of .tar.gz files

### PR DESCRIPTION
**Pull request by rschroll**
I don't know if you're interested in this change or not, but in my experience, people are more familiar with zipfiles than tarfiles.  The changes are pretty minimal, so we could imagine keeping both and making the format a configuration option, but that struck me as more trouble than it was worth.  If you'd like it, let me know.

This is built atop #11, for no reason other than that I stumbled across that while working on this.

### CODE REVIEW

**Comment by yuvipanda** [comment]
Do you think you can make it do both? We can default to ZIP!

**Comment by rschroll** [comment]
It should be fairly easy.  Is it possible to set configuration options during the nbextension enable?  That would be the best way to give people the option without cluttering the interface too much.

**Comment by rschroll** [comment]
This is most of the way there.  Both zip and tar.gz file downloads are provided, with a format argument to the endpoint determining which to use.  Nothing is set up on the browser side to specify which to use, though, so zip is used by default.

It seems like the right way to do this is through the ConfigManager, as in other nbextensions ([like so](https://github.com/ipython-contrib/jupyter_contrib_nbextensions/tree/e8d66d2a11e119831cd700bc4bce9886789e2da6/src/jupyter_contrib_nbextensions/nbextensions/limit_output)).  But the notebook config isn't exposed on the directory pages.  The docs suggest that the "tree" config is the right one to use, but I couldn't find that exposed via javascript either.

**Comment by rschroll** [comment]
@yuvipanda Was going through old PRs and noticed this was still open.  Basically, I think everything's set up on the backend.  But I don't see a way to get at ConfigManager settings in the JS of directory pages.  Can you point me in the right direction?

**Comment by ryanlovett** [comment]
@rschroll Does the file format choice need to be exposed in the tree listing? Like is it sufficient for there to be one download button and that retrieves the file in whatever format the admin configured?

**Comment by ryanlovett** [comment]
@rschroll Otherwise I suppose you could expose the config choice via a handler in the extension that the JS calls.

**Comment by rschroll** [comment]
I'm afraid I don't understand what you're suggesting.  The backend code already has an choice via the `format` option.  I'm trying to figure out how let the front-end code get the user configuration about which option to use.  As I understand it, this would let the user switch settings via the jupyter_nbextensions_configurator.

Are you suggesting that the backend code should just read the config file itself, and not expose the `format` option?  I presume that would work, but I'm not sure if it would cooperate with the configurator.

**Comment by ryanlovett** [comment]
Ah, I was suggesting a less flexible option in that the hub admin would configure the file format and the handler would query that setting.

**Comment by betatim** [comment]
@rschroll do you want to pick this up again or would it be Ok if I tried to get this merged? Would like to have `zip` support.

**Comment by rschroll** [comment]
I'm traveling this week, so I won't be able to look at it right away. If
you want to work on it, go ahead. Otherwise, I'll take a look next week.

Thanks for following up!

**Comment by rschroll** [comment]
@betatim Thanks so much for getting this in!  I don't think this PR adds anything at this point, so I'll close it.

**Pull request closed without merging**
