### PR TITLE
Nbzip with zip only

### PR DESCRIPTION
**Pull request by betatim**
This mostly cleans up the tests a bit and renames some labels for the download button.

It would be nice to have a dropdown menu with the two options so users can choose. However my jquery skills aren't good enough to work out how to do that nicely.

This is a follow on from #12

### CODE REVIEW

**Comment by betatim** [comment]
@ryanlovett can we merge this or would you prefer to have `.tar.gz`?

**Comment by ryanlovett** [comment]
+1 for merging!

**Comment by betatim** [comment]
I assumed you had the power to make it so :) Do you know who we need to ping who has sufficient privilege?

**Comment by ryanlovett** [comment]
Oh, I've got the power too. Here we go...

**Comment by betatim** [comment]
Thanks!

**Pull request merged**
